# Jira Agent Configurations ----------------------------------------------------

EpicAgent:
  name: EpicAgent
  description: Fetches all Jira Epics.
  prompt_key: epic_prompt
  schema: EpicList
  requires_initial_state: false
  markdown: false

StoryAgent:
  name: StoryAgent
  description: Reads Epic data and retrieves Stories/tasks under each Epic.
  prompt_key: story_prompt
  schema: StoryList
  requires_initial_state: True
  markdown: false

IssueAgent:
  name: IssueAgent
  description: Reads Story data provided and fetches metadata from Jira Issues.
  prompt_key: issue_prompt
  schema: IssueList
  requires_initial_state: True
  markdown: false


# GitHub Agent Configurations --------------------------------------------------

RepoAgent:
  name: RepoAgent
  description: Discovers GitHub repositories for the given org/user.
  prompt_key: repo_prompt
  schema: RepoList
  requires_initial_state: True
  markdown: false

BranchAgent:
  name: BranchAgent
  description: Discovers branches for the given GitHub repository via PRs.
  prompt_key: branch_prompt
  schema: null
  requires_initial_state: True
  markdown: false

PRNAgent:
  name: PRNumbersAgent
  description: Identifies relevant PR numbers for a repo based on update time.
  prompt_key: pr_numbers_prompt
  schema: PRNumbers
  requires_initial_state: True
  markdown: false

PRDAgent:
  name: PRDetailsAgent
  description: Fetches detailed information for a list of PR numbers.
  prompt_key: pr_details_prompt
  schema: PRDetails
  requires_initial_state: True
  markdown: false

PRCAgent:
  name: PRCommitsAgent
  description: Gathers commit objects and status-check results for a PR.
  prompt_key: pr_commits_prompt
  schema: PRCommits
  requires_initial_state: True
  markdown: false


# ArangoDB Agent Configurations ------------------------------------------------

GraphAgent:
  name: GraphAgent
  description: Updates the ArangoDB graph with the input data.
  prompt_key: null
  schema: null
  requires_initial_state: true
  markdown: false