vertex_collections:

  # Jira nodes -----------------------------------------------------------------
  - Epics
  - Projects
  - Stories
  - Persons
  - Teams
  - Sprints

  # GitHub nodes ---------------------------------------------------------------
  - Branches
  - Commits
  - GitHubUsers
  - PullRequests
  - Repositories


edge_collections:

  # Jira Edges -----------------------------------------------------------------
  - name: epic_of_project
    from: [Epics]
    to: [Projects]

  - name: story_belongs_to_epic
    from: [Stories]
    to: [Epics]

  - name: assigned_to
    from: [Stories]
    to: [Persons]

  - name: reported_by
    from: [Stories]
    to: [Persons]

  - name: member_of
    from: [Persons]
    to: [Teams]

  - name: team_works_on_epic
    from: [Teams]
    to: [Epics]

  - name: team_works_on_project
    from: [Teams]
    to: [Projects]

  - name: issue_in_sprint
    from: [Stories]
    to: [Sprints]


  # GitHub Edges ---------------------------------------------------------------
  - name: pr_in_repo
    from: [PullRequests]
    to: [Repositories]

  - name: pr_authored_by
    from: [PullRequests]
    to: [GitHubUsers]

  - name: pr_reviewed_by
    from: [PullRequests]
    to: [GitHubUsers]

  - name: commit_in_pr
    from: [Commits]
    to: [PullRequests]

  - name: commit_on_branch
    from: [Commits]
    to: [Branches]

  - name: commit_authored_by
    from: [Commits]
    to: [GitHubUsers]


  # Cross-System Edges ---------------------------------------------------------
  - name: pr_for_issue
    from: [PullRequests]
    to: [Stories]

  - name: commit_for_issue 
    from: [Commits]
    to: [Stories]

  - name: same_as
    from: [Persons]
    to: [GitHubUsers]