MODELS:
  google:
    epic: "gemini-2.0-flash"
    story: "gemini-2.5-pro-exp-03-25"
    issue: "gemini-2.0-flash"
    graph: "gemini-2.0-flash-lite"

  openai:
    epic: "gpt-4.1-nano"
    story: "gpt-4.1-nano"
    issue: "gpt-4.1-nano"
    graph: "gpt-4o-mini"

    repo: "gpt-4.1-nano"
    pr: "gpt-4.1-nano"
    review: "gpt-4.1-nano"
    commit: "gpt-4.1-nano"


SESSION:
  session_id: "org_chart_run"
  max_concurrency: 20
  state_epics: "epics_data_input"
  state_stories: "stories_data_input"
  state_issues: "issues_data_input"


PROMPTS:
  epic: "epic_prompt"
  story: "story_prompt"
  issue: "issue_prompt"
  graph_epic: "epic_graph_prompt"
  graph_story: "story_graph_prompt"
  graph_issue: "issue_graph_prompt"

  repo: "repo_prompt"
  pr: "pr_prompt"
  review: "review_prompt"
  commit: "commit_prompt"

GITHUB:
  org: "xpander-ai"


MCP_SERVERS:
  github: "ghcr.io/github/github-mcp-server:latest"