MODELS:
  google:
    epic: "gemini-2.0-flash"
    story: "gemini-2.5-pro-exp-03-25"
    issue: "gemini-2.0-flash"
    graph: "gemini-2.0-flash-lite"

  openai:
    epic: "gpt-4.1-nano"
    story: "gpt-4.1-nano"
    issue: "gpt-4.1-nano"
    graph: "gpt-4.1-mini"

SESSION:
  session_id: "org_chart_run"
  state_epics: "epics_data_input"
  state_stories: "stories_data_input"
  state_issues: "issues_data_input"
