assignee: Assignee
created: Created
development: Development
issue_size: Issue Size
issuetype: Issue Type
key: Issue key
parent: Parent
priority: Priority
project: Project
reporter: Reporter
resolution: Resolution
resolutiondate: Resolved
severity: Severity
sprint: Sprint
status: Status
story_points: Story Points
summary: Summary
team: Team Name
updated: Updated
