assignee: assignee
created: created
development: customfield_10000
issue_size: customfield_10124
issuetype: issuetype
key: issuekey
parent: parent
priority: priority
project: project
reporter: reporter
resolution: resolution
resolutiondate: resolutiondate
severity: customfield_10188
sprint: customfield_10008
status: status
story_points: customfield_10038
summary: summary
team: customfield_10162
updated: updated
