assignee: assignee
created: created
issue_size: customfield_10124
issuetype: issuetype
key: issuekey
priority: priority
project: project
reporter: reporter
resolution: resolution
resolutiondate: resolutiondate
sprint: customfield_10008
status: status
story_points: customfield_10038
summary: summary
team: customfield_10162
updated: updated
