# Global Test Setup Params -----------------------------------------------------

provider: google
debug: true
input_dir: ../test_data
output_dir: ../test_output


# Jira Agent Tests -----------------------------------------------------------

epic:
  agent_type: EpicAgent
  model_key: epic
  tools: jira_search
  session_id: test_session_EpicAgent
  input_file: null
  input_state_key: null
  prompt_key: null
  trigger_message: Get Epics for the Jira org
  response_model: False
  schema: EpicList

story:
  agent_type: StoryAgent
  model_key: story
  tools: jira_epic_issues
  session_id: test_session_StoryAgent
  input_file: test_epic_data.json
  input_state_key: epics_data_input
  prompt_key: null
  trigger_message: Get stories/tasks from the input Jira Epics
  response_model: False
  schema: StoryList

issue:
  agent_type: IssueAgent
  model_key: issue
  tools: jira_get_issue
  session_id: test_session_IssueAgent
  input_file: test_story_data.json
  input_state_key: stories_data_input
  prompt_key: null
  trigger_message: Find issue details based on input data
  response_model: False
  schema: IssueList


# Jira Graph Agent Tests -------------------------------------------------------

graph_epic:
  agent_type: GraphAgent
  model_key: graph
  tools: arango_upsert
  session_id: test_session_GraphAgent
  input_file: test_epic_data.json
  input_state_key: epics_data_input
  prompt_key: epic_graph_prompt
  trigger_message: Add input data to the ArangoDB graph using the available tool
  response_model: False
  schema: null

graph_story:
  agent_type: GraphAgent
  model_key: graph
  tools: arango_upsert
  session_id: test_session_GraphAgent
  input_file: test_story_data.json
  input_state_key: stories_data_input
  prompt_key: story_graph_prompt
  trigger_message: Add input data to the ArangoDB graph using the available tool
  response_model: False
  schema: null

graph_issue:
  agent_type: GraphAgent
  model_key: graph
  tools: arango_upsert
  session_id: test_session_GraphAgent
  input_file: test_issue_data.json
  input_state_key: issues_data_input
  prompt_key: issue_graph_prompt
  trigger_message: Add input data to the ArangoDB graph using the available tool
  response_model: False
  schema: null


# GitHub Agent Tests -----------------------------------------------------------

repo:
  agent_type: RepoAgent
  model_key: repo
  session_id: test_session_RepoAgent
  input_file: test_org_data.json
  input_state_key: org_or_user
  trigger_message: Scan GitHub org for active repos
  response_model: True
  cutoff: 30

branch:
  agent_type: BranchAgent
  model_key: pr
  session_id: test_session_BranchAgent
  input_file: test_repo_data.json
  input_state_key: repo_data_input
  trigger_message: Fetch branches for the given repository
  response_model: True
  cutoff: null

pr_numbers:
  agent_type: PRNAgent
  model_key: pr
  session_id: test_session_PRNumbersAgent
  input_file: test_repo_data.json
  input_state_key: input_repo_data
  trigger_message: Discover pull requests for the given repo since cutoff date
  response_model: True
  cutoff: 1

pr_details:
  agent_type: PRDAgent
  model_key: pr
  session_id: test_session_PRDetailsAgent
  input_file: test_pr_number_data.json
  input_state_key: input_pr_number_data
  trigger_message: Fetch detailed PR information for the given PR numbers
  response_model: True
  cutoff: null

commit:
  agent_type: PRCAgent
  model_key: pr
  session_id: test_session_PRCommitsAgent
  input_file: test_pr_details_data.json
  input_state_key: input_pr_details_data
  trigger_message: Fetch commit information for the given PR data
  response_model: True
  cutoff: null
