models:
  google:
    epic: "gemini-2.0-flash"
    story: "gemini-2.5-pro-exp-03-25"
    issues: "gemini-2.0-flash"
    graph: "gemini-2.0-flash-lite"

  openai:
    epic: "gpt-4o-mini"
    story: "gpt-4o-mini"
    issues: "gpt-4o-mini"
    graph: "gpt-4o-mini"