- name: Product
  description: The product being analyzed
  examples: '{"name": "Clarity", "category": "Voice Processing"}'
  attributes:
    - name: id
      type: string
    - name: name
      type: string
    - name: description
      type: string
    - name: category
      type: string
    - name: targetMarkets
      type: string[]

- name: Region
  description: Geographic regions for market analysis
  examples: '{"name": "Americas", "marketSize": 120000000}'
  attributes:
    - name: id
      type: string
    - name: name
      type: string
    - name: marketSize
      type: number
    - name: countries
      type: string[]

- name: Country
  description: Individual countries within regions
  examples: '{"name": "United States", "potentialUsers": 50000000}'
  attributes:
    - name: id
      type: string
    - name: name
      type: string
    - name: population
      type: number
    - name: potentialUsers
      type: number

- name: Enterprise
  description: Potential business customers/resellers
  examples: '{"name": "Verizon", "type": "Telecom", "userBase": 30000000}'
  attributes:
    - name: id
      type: string
    - name: name
      type: string
    - name: type
      type: string
    - name: operatingCountries
      type: string[]  # list of country names
    - name: userBase
      type: number

- name: Competitor
  description: Companies offering competing products
  examples: '{"name": "AudioClear", "strengths": ["Established partnerships"]}'
  attributes:
    - name: id
      type: string
    - name: name
      type: string
    - name: productOfferings
      type: string[]
    - name: strengths
      type: string[]
    - name: weaknesses
      type: string[]

- name: MarketTrend
  description: Emerging trends affecting the product
  examples: '{"name": "Edge-based processing", "timeframe": "1-2 years"}'
  attributes:
    - name: id
      type: string
    - name: name
      type: string
    - name: description
      type: string
    - name: timeframe
      type: string
    - name: impact
      type: string

- name: Company
  description: Represents the primary business entity being researched or a competitor.
  examples: '{"name": "Nvidia Corporation", "description": "Designs GPUs for gaming and professional markets..."}'
  attributes:
    - name: name
      type: string
    - name: description
      type: string