tavily_search_params:
  search_depth: "basic"
  max_results: 3
  time_range: "month" # consider if this should be dynamic or configured
  topic: "general"
  include_raw_content: True

# Number of search queries per company
N_searches: 3

# Number of revisions to the final output
N_revisions: 0

# Choice of output schema to use
schema_id_to_use: "COMPANY_OVERVIEW_GRAPH"

# Define mappings from schema keys to graph collection names 
# Should match 'name' field in entity_types.yaml and relationship_types.yaml
collection_mappings:
  entities:
    company: Company
    product: Product
    competitor: Competitor
    region: Region
    
  relationships:
    develops: develops
    competes_with: competes_with
    operates_in: operates_in