tavily_search_params:
  search_depth: "basic"
  max_results: 3
  time_range: "month" # consider if this should be dynamic or configured
  topic: "general"
  include_raw_content: True

# Number of search queries per company
N_searches: 3

# Number of revisions to the final output
N_revisions: 0

# Choice of output schema to use
schema_id_to_use: "COMPANY_OVERVIEW_GRAPH"