tavily_search_params:
  search_depth: "basic"
  max_results: 3
  time_range: "month" # consider if this should be dynamic or configured
  topic: "general"
  include_raw_content: True

# Number of search queries per company
N_searches: 1

# Number of revisions to the final output
N_revisions: 0