- conflict_resolution: 'prefer_newer: true, merge_non_conflicting: true'
  entity_type: All
  update_conditions: 'scheduled: true, on_demand: true'
  update_frequency: daily
  versioning: 'keep_versions: 3, track_changes: true'
- conflict_resolution: 'require_confirmation: true, highlight_changes: true'
  entity_type: Competitor
  update_conditions: 'scheduled: true, on_significant_change: true'
  update_frequency: weekly
  versioning: 'keep_versions: 5, track_strengths_weaknesses_changes: true'
- conflict_resolution: 'append_new_trends: true, update_existing_trends: true'
  entity_type: MarketTrend
  update_conditions: 'scheduled: true, on_new_trend_detection: true'
  update_frequency: monthly
  versioning: 'keep_versions: 12, track_impact_changes: true'
